### ISSUE TITLE
stderr: 'fatal: destination path '/usr/src/nginx/modules/ngx_http_substitutions_filter_module' already exists and is not an empty directory.

### ISSUE THREAD

**Issue by patsevanton** [TinkoffCreditSystems/Nginx-builder#10]
```
lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core
```

When run second time get error:

```
./main.py build -f example.config.yaml 
builder - INFO - Parse yaml file: example.config.yaml
builder - INFO - /usr/src/nginx dir already exist
builder - INFO - Download scripts for build rpm package
builder - INFO - Running command: rpmdev-setuptree
builder - INFO - 
builder - INFO - Downloading nginx src...
builder - INFO - Running command: rpm --upgrade --verbose --hash http://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.13.9-1.el7_4.ngx.src.rpm
warning: /var/tmp/rpm-tmp.LZDJZS: Header V4 RSA/SHA1 Signature, key ID 7bd9bf62: NOKEY
warning: user builder does not exist - using root
warning: group builder does not exist - using root
builder - INFO - Retrieving http://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.13.9-1.el7_4.ngx.src.rpm
Updating / installing...
nginx-1:1.13.9-1.el7_4.ngx            ########################################

builder - INFO - Downloading 3d-party modules...
builder - INFO - /usr/src/nginx/modules dir already exist
builder - INFO - Module nginx-auth-ldap will download by branch
builder - ERROR - Cmd('git') failed due to: exit code(128)
  cmdline: git clone --branch=master -v https://github.com/kvspb/nginx-auth-ldap.git /usr/src/nginx/modules/nginx-auth-ldap
  stderr: 'fatal: destination path '/usr/src/nginx/modules/nginx-auth-ldap' already exists and is not an empty directory.
'
```

**Comment by therb1** [comment]
Вы пытались запустить скрипт дважды без удаления '/usr/src/nginx'. Мы предполагаем что данный инструмент делает всё сам без использования человеческой помощи и запускается в docker контейнере. Для того что бы исправит данную ошибку удалите '/usr/src/nginx'. Сделано это для того что бы у человека небывало возможности вносить изменения локально без использования конфиге.

**Comment by therb1** [comment]
Если данное решение вам не помогло. Отпишитесь пожалуйста сюда.

**Comment by patsevanton** [comment]
Может быть сделать удаление директории /usr/src/nginx' ?

**Comment by therb1** [comment]
Мы думали над этим, но решили если человек видит данную ошибку он должен знать что делает, что-то не так и может выстрелить себе в ногу. Мы также не знаем на каких системах будет запускаться наше приложение и не имеем морального права удалять что-то из системы. Вдруг человек собирал эти модули годами или не дай бог писал модуль к NGINX у себя на локальной машине не делая бекапов последние 5 дней. Звучит бредово, но именно такие ситуации иногда случаются.

**Comment by patsevanton** [comment]
А может вот эту директорию удалять /usr/src/nginx/modules/nginx-auth-ldap?

**Comment by therb1** [comment]
Тут все очень 'depends on' люди иногда вносят изменения в локальные модули тоже и мы не хотели бы влиять на что-то находящееся на конечной машине на которой производится сборка. Наш инструмент предназначен для сборки в автоматизированном режиме и не имеет интерактивного режима в котором мы могли бы пообщаться с пользователем. Без интерактивного режима принимать решения о том что является не важным для конечного пользователя мы не можем.

**Comment by patsevanton** [comment]
Понял. Спасибо.
