### ISSUE TITLE
Cannot find nginx source rpm(SRPM) with version 1.16.0 in url http://nginx.org/packages/mainline/centos/7/SRPMS

### ISSUE THREAD

**Issue by patsevanton** [TinkoffCreditSystems/Nginx-builder#11]
Пытаюсь собрать 16 версию nginx

```
cat config.yaml 
nginx_version: 1.16.0
output_package: rpm
modules:
  - module:
      name: nginx-dav-ext-module
      git_url: https://github.com/arut/nginx-dav-ext-module.git
      git_tag: v3.0.0
```

```
./main.py build -f config.yaml 
builder - INFO - Parse yaml file: config.yaml
builder - INFO - Download scripts for build rpm package
builder - INFO - Running command: rpmdev-setuptree
builder - INFO - 
builder - INFO - Downloading nginx src...
builder - ERROR - Cannot find nginx source rpm(SRPM) with version 1.16.0 in url http://nginx.org/packages/mainline/centos/7/SRPMS
```

Может добавить использование https://nginx.org/download/nginx-1.16.0.tar.gz ?
Например, код взять из https://nginx.org/download/nginx-1.16.0.tar.gz, а остальные файлы с с других SRPM ( http://nginx.org/packages/mainline/centos/7/SRPMS/nginx-1.15.9-1.el7_4.ngx.src.rpm )?

**Comment by patsevanton** [comment]
Если использовать конфиг из статьи https://habr.com/ru/company/tinkoff/blog/452336/ с rpm, то будет похожая ошибка

```
./main.py build -f config.yaml 
builder - INFO - Parse yaml file: config.yaml
builder - INFO - /usr/src/nginx dir already exist
builder - INFO - Download scripts for build rpm package
builder - INFO - Running command: rpmdev-setuptree
builder - INFO - 
builder - INFO - Downloading nginx src...
builder - ERROR - Cannot find nginx source rpm(SRPM) with version 1.14.1 in url http://nginx.org/packages/mainline/centos/7/SRPMS
```

**Comment by patsevanton** [comment]
Находятся они в другом месте:

http://nginx.org/packages/centos/7/SRPMS/

**Comment by patsevanton** [comment]
Попробую сделать PR

**Comment by patsevanton** [comment]
PR https://github.com/TinkoffCreditSystems/Nginx-builder/pull/13

**Comment by javdet** [comment]
Добрый день, спасибо за PR. Эта же проблема присутствует для deb пакетов. Готовлю исправления для обоих случаев.

**Comment by patsevanton** [comment]
Я могу попробовать сделать PR.
Что нужно поправить в моем PR?

**Comment by javdet** [comment]
Сделал единый подход к выбору stable и mainline версий для deb и rpm. Изменения уже в мастере #15
