### ISSUE TITLE
[Question] Is it possible to specify the version of OpenSSL ?

### ISSUE THREAD

**Issue by BROBIRD** [TinkoffCreditSystems/Nginx-builder#29]
[Reason] I'd like to build a NGINX RPM package with TLS1.3 Support.

Thanks!

**Comment by javdet** [comment]
Hello! You should 
- install openssl v1.1.1 or higher 
- add build parameter --with-openssl-opt='enable-tls1_3' to config like this https://github.com/TinkoffCreditSystems/Nginx-builder/blob/master/example.config.yaml#L72

**Comment by BROBIRD** [comment]
> 
> 
> Hello! You should
> 
>     * install openssl v1.1.1 or higher
> 
>     * add build parameter --with-openssl-opt='enable-tls1_3' to config like this https://github.com/TinkoffCreditSystems/Nginx-builder/blob/master/example.config.yaml#L72

Hi! 
Thank you for reply!
In fact, it seems impossible to install OpenSSL 1.1+ in CentOS7 using yum.
So, I modified your python script to specify the source path of OpenSSL.
And  `parameter --with-openssl-opt='enable-tls1_3'` is not necessary, because tls1.3 is enabled by default in OpenSSL 1.1.1+.

**Comment by javdet** [comment]
Yes you right. OpenSSL 1.1+ can be built from source in CentOS 7. Centos 8 always have OpenSSL 1.1.1

**Comment by therb1** [comment]
@BROBIRD If you have other questions, please reopen issue.
