### ISSUE TITLE
Question: Additional dependencies for build

### ISSUE THREAD

**Issue by rakhinskiy** [TinkoffCreditSystems/Nginx-builder#32]
What can I do if module require some library unpacked in module dir?
For example pagespeed require psol (I need download psol-${version}-x64.tar.gz and unpack it to pagespeed module folder) 

Can I build modules as dynamic and pack it to separate rpm / deb packages?

**Comment by therb1** [comment]
Hi @rakhinskiy sorry for not answering for so long.
At the moment we do not have such functionality, and we have not planned to do it yet, but we are always open to contributions from the community. If you send your PR it will be great.
