### ISSUE TITLE
Can not build when using 'local_url'

### ISSUE THREAD

**Issue by alexey107** [TinkoffCreditSystems/Nginx-builder#35]
**Describe the bug**
Can not build when using 'local_url'
If this archive is on a web (s3) and using 'web_url' it builds ok.

**To Reproduce**
config example:
nginx_version: 1.14.0
output_package: deb
modules:
  - module:
      name: ngx_pagespeed
      local_url: /root/ngx_pagespeed/incubator-pagespeed-ngx-1.13.35.2-stable.tar.gz
      dependencies:
        - debhelper
        - dh-systemd
        - quilt
        - libssl-dev
        - libpcre3-dev
        - zlib1g-dev
        - uuid-dev

**Screenshots**
builder - INFO - Parse yaml file: config.yaml
builder - INFO - Download scripts for build deb package
builder - INFO - Downloading nginx src...
builder - INFO - --> http://nginx.org/download/nginx-1.14.0.tar.gz
builder - INFO - Downloading 3d-party modules...
builder - ERROR - 'str' object is not callable

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by therb1** [comment]
Fixed in PR
https://github.com/TinkoffCreditSystems/Nginx-builder/pull/36

**Comment by therb1** [comment]
@Taraflex @alexey107  FYI
