### ISSUE TITLE
неверный формат архива tar.gz 

### ISSUE THREAD

**Issue by stepansantalov** [TinkoffCreditSystems/Nginx-builder#5]
При попытке сборки ловлю сообщение:

~/Nginx-builder$ ./main.py build  -f banana-config.yaml 
builder - INFO - Parse yaml file: banana-config.yaml
builder - INFO - /usr/src/nginx dir already exist
builder - INFO - Download scripts for build deb package
builder - INFO - Downloading nginx src...
builder - INFO - --> http://nginx.org/download/nginx-1.16.tar.gz
builder - INFO - Downloading 3d-party modules...
builder - INFO - /usr/src/nginx/modules dir already exist
builder - INFO - Module nginx_cookie_flag will download by branch
builder - INFO - -- Done: nginx_cookie_flag
builder - INFO - Downloading dependencies
builder - INFO - Building .deb package
builder - ERROR - Archive format nginx-1.16.tar.gz is not valid
builder - ERROR - 'NoneType' object has no attribute 'rstrip'

**Comment by therb1** [comment]
Покажите пожалуйста **banana-config.yaml**

Скорее всего проблема в том что в версии вы указали **nginx_version: 1.16**

Для устранения проблемы измените эту переменную на **1.16.0**

Мы не можем в здесь обогащать информацию о версии так как невозможно определить какую именно версию вы хотите **0.1.16** или **1.1.16** или **1.16.0**

**Если помогло отпишитесь пожалуйста сюда**

**Comment by stepansantalov** [comment]
Да, действительно, версию указывал 1.16, указал 1.16.0 проблема ушла.
